name: Build & Publish

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '**/Cargo.lock'
      - '**/Cargo.toml'
jobs:
  build:
    strategy:
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1

    - name: Install Cargo Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true

    - name: Cargo Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose

    - name: Cargo Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose

    - run: mkdir dist
    - run: cp target/release/mrrobot dist/mrrobot
    - run: cp target\release\mrrobot.exe dist\mrrobot.exe
      if: failure()
    
    - name: Upload binary (*nix)
      uses: actions/upload-artifact@v1
      with:
        name: mrrobot-amd64-${{ runner.os }}
        path: dist/mrrobot

    - name: Upload binary (NT)
      uses: actions/upload-artifact@v1
      with:
        name: mrrobot-amd64-${{ runner.os }}
        path: dist/mrrobot.exe